name: Docker Image CI Release

on:
  push:
    tags:
      - "v*.*.*"
  schedule:
    - cron: '0 4 * * 0' # This will run the workflow every Sunday at 4 am

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkout the latest tag if exists
        run: git checkout ${{ env.latest_tag }}

      - name: Get the commit ID
        id: get_commit
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Inject version and commit ID into index.ejs
        run: |
          VERSION=${{ env.latest_tag }}
          COMMIT=${{ env.commit }}
          echo "<!-- Version: $VERSION, Commit ID: $COMMIT -->" >> views/index.ejs

      - name: Docker meta
        id: meta
        if: env.latest_tag != ''
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          # list of Docker images to use as base name for tags
          images: |
            wemove/read2burn
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

